-- Author metadata source layer: extraction runs, their per-book items and
-- attempts, immutable metadata snapshots and contributor credits, and the
-- explicit pilot approval that gates a full run.
--
-- Nothing here touches the reader model. opds_catalog_book is only referenced:
-- every foreign key into it restricts deletion, so neither the legacy book nor
-- the source history can disappear as a side effect of the other.
--
-- Status and enum values are closed by CHECK constraints rather than lookup
-- tables; the constraint names are part of the contract the schema tests pin.

-- Creating a foreign key takes a SHARE ROW EXCLUSIVE lock on the referenced
-- tables. Fail fast instead of queueing behind a long scan transaction.
SET LOCAL lock_timeout = '5s';

-- Shared guard for the immutable tables. A DELETE is always refused. An UPDATE
-- is refused unless every column outside the trigger's argument list stays the
-- same, so the arguments name the only columns that may change — none for the
-- fully immutable tables. The message names the table, never the row values:
-- source rows carry author names.
CREATE FUNCTION public.author_metadata_reject_mutation() RETURNS trigger
    LANGUAGE plpgsql AS $$
DECLARE
    -- TG_ARGV is NULL, not empty, when the trigger has no arguments; a NULL
    -- here would turn both sides of the comparison into NULL and let any
    -- UPDATE through.
    mutable text[] := coalesce(TG_ARGV, '{}'::text[]);
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'rows of % are immutable and cannot be deleted', TG_TABLE_NAME
            USING ERRCODE = 'restrict_violation';
    END IF;
    IF (to_jsonb(OLD) - mutable) IS DISTINCT FROM (to_jsonb(NEW) - mutable) THEN
        RAISE EXCEPTION 'rows of % are immutable; only % may change', TG_TABLE_NAME, mutable
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END
$$;

-- An attempt may be finished exactly once; after that it is history.
CREATE FUNCTION public.author_metadata_reject_closed_attempt() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF OLD.finished_at IS NOT NULL THEN
        RAISE EXCEPTION 'rows of % are immutable once finished', TG_TABLE_NAME
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END
$$;

-- One extraction run. Versions are exact strings: a run never mixes extractor
-- or normalizer versions.
CREATE TABLE public.author_metadata_run (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mode                    TEXT NOT NULL,
    status                  TEXT NOT NULL DEFAULT 'pending',
    extractor_version       TEXT NOT NULL,
    normalizer_version      TEXT NOT NULL,
    selector_book_ids       BIGINT[],
    selector_archive        TEXT,
    items_total             INTEGER NOT NULL DEFAULT 0,
    items_terminal          INTEGER NOT NULL DEFAULT 0,
    last_error_class        TEXT,
    -- The admin who started the run. Like book_match_decisions, it names who
    -- acted rather than belonging to them, so deleting the account keeps the
    -- run and forgets the reference.
    created_by_user_id      BIGINT REFERENCES public.auth_user (id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at              TIMESTAMPTZ,
    extraction_completed_at TIMESTAMPTZ,
    finished_at             TIMESTAMPTZ,

    CONSTRAINT author_metadata_run_mode_check
        CHECK (mode IN ('smoke', 'pilot_archive', 'full')),
    CONSTRAINT author_metadata_run_status_check
        CHECK (status IN ('pending', 'running', 'paused', 'completed', 'failed_systemic')),
    CONSTRAINT author_metadata_run_extractor_version_check
        CHECK (extractor_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    CONSTRAINT author_metadata_run_normalizer_version_check
        CHECK (normalizer_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    -- smoke and pilot_archive name exactly one selector; full names none and
    -- covers the catalog.
    CONSTRAINT author_metadata_run_selector_check
        CHECK (CASE mode
                   WHEN 'full' THEN num_nonnulls(selector_book_ids, selector_archive) = 0
                   ELSE num_nonnulls(selector_book_ids, selector_archive) = 1
               END),
    CONSTRAINT author_metadata_run_selector_book_ids_check
        CHECK (selector_book_ids IS NULL
               OR (cardinality(selector_book_ids) > 0
                   AND array_position(selector_book_ids, NULL) IS NULL
                   AND 0 < ALL (selector_book_ids))),
    CONSTRAINT author_metadata_run_selector_archive_check
        CHECK (selector_archive IS NULL OR btrim(selector_archive) <> ''),
    CONSTRAINT author_metadata_run_counters_check
        CHECK (items_total >= 0 AND items_terminal >= 0 AND items_terminal <= items_total),
    -- A closed class, never free error text.
    CONSTRAINT author_metadata_run_error_class_check
        CHECK (last_error_class IS NULL OR last_error_class ~ '^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT author_metadata_run_finished_check
        CHECK ((status IN ('completed', 'failed_systemic')) = (finished_at IS NOT NULL)),
    CONSTRAINT author_metadata_run_completed_check
        CHECK (status <> 'completed' OR extraction_completed_at IS NOT NULL),
    -- Target of the pilot approval's composite foreign key: an approval pins
    -- the run's mode, status and versions, so none of them can change after it.
    CONSTRAINT author_metadata_run_approval_key
        UNIQUE (id, mode, status, extractor_version, normalizer_version)
);

-- At most one active extraction run, enforced by PostgreSQL rather than by the
-- memory of whichever pod started it. paused is active: it resumes the same run.
CREATE UNIQUE INDEX author_metadata_run_one_active
    ON public.author_metadata_run ((true))
    WHERE status IN ('pending', 'running', 'paused');

CREATE TRIGGER author_metadata_run_updated_at
    BEFORE UPDATE ON public.author_metadata_run
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- The applied result of one extractor version to one file version of one book.
-- Payload columns are immutable; is_current is the only column that may change.
CREATE TABLE public.book_metadata_snapshot (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id                 BIGINT NOT NULL REFERENCES public.opds_catalog_book (id) ON DELETE RESTRICT,
    book_md5                TEXT NOT NULL,
    extractor_version       TEXT NOT NULL,
    -- backfill snapshots belong to a run; a live snapshot is written by the
    -- scan transaction that adds a new book and has none.
    origin                  TEXT NOT NULL,
    run_id                  BIGINT REFERENCES public.author_metadata_run (id) ON DELETE RESTRICT,
    outcome                 TEXT NOT NULL,
    archive_path            TEXT NOT NULL,
    entry_name              TEXT NOT NULL,
    xml_provenance          JSONB NOT NULL DEFAULT '{}'::jsonb,
    source_title            TEXT,
    source_lang             TEXT,
    source_src_lang         TEXT,
    source_isbns            TEXT[] NOT NULL DEFAULT '{}',
    source_publisher        TEXT,
    source_city             TEXT,
    source_year             TEXT,
    source_document_id      TEXT,
    source_document_version TEXT,
    source_sequences        JSONB NOT NULL DEFAULT '[]'::jsonb,
    quality_flags           TEXT[] NOT NULL DEFAULT '{}',
    is_current              BOOLEAN NOT NULL DEFAULT true,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT book_metadata_snapshot_key
        UNIQUE (book_id, book_md5, extractor_version),
    -- Target of the run item's composite foreign key: an item can only point
    -- at a snapshot of its own book.
    CONSTRAINT book_metadata_snapshot_id_book_key
        UNIQUE (id, book_id),
    CONSTRAINT book_metadata_snapshot_book_md5_check
        CHECK (book_md5 ~ '^[0-9a-f]{32}$'),
    CONSTRAINT book_metadata_snapshot_extractor_version_check
        CHECK (extractor_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    CONSTRAINT book_metadata_snapshot_origin_check
        CHECK (origin IN ('backfill', 'live')),
    CONSTRAINT book_metadata_snapshot_origin_run_check
        CHECK ((origin = 'backfill' AND run_id IS NOT NULL)
               OR (origin = 'live' AND run_id IS NULL)),
    CONSTRAINT book_metadata_snapshot_outcome_check
        CHECK (outcome IN ('extracted', 'extracted_no_author')),
    CONSTRAINT book_metadata_snapshot_provenance_check
        CHECK (archive_path <> '' AND entry_name <> '' AND jsonb_typeof(xml_provenance) = 'object'),
    CONSTRAINT book_metadata_snapshot_isbns_check
        CHECK (array_position(source_isbns, NULL) IS NULL),
    CONSTRAINT book_metadata_snapshot_sequences_check
        CHECK (jsonb_typeof(source_sequences) = 'array'),
    CONSTRAINT book_metadata_snapshot_quality_flags_check
        CHECK (array_position(quality_flags, NULL) IS NULL)
);

-- At most one current snapshot per book.
CREATE UNIQUE INDEX book_metadata_snapshot_one_current
    ON public.book_metadata_snapshot (book_id)
    WHERE is_current;

CREATE INDEX book_metadata_snapshot_run_idx
    ON public.book_metadata_snapshot (run_id)
    WHERE run_id IS NOT NULL;

CREATE TRIGGER book_metadata_snapshot_immutable
    BEFORE UPDATE OR DELETE ON public.book_metadata_snapshot
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation('is_current');

-- One non-empty title-info/author or title-info/translator element of one
-- snapshot. Fully immutable: the selected normalization result lives in a
-- separate selection table, not here.
CREATE TABLE public.book_contributor_credit (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id         BIGINT NOT NULL REFERENCES public.book_metadata_snapshot (id) ON DELETE RESTRICT,
    role                TEXT NOT NULL,
    -- Zero-based, separately within each role, in XML order.
    position            INTEGER NOT NULL,
    -- NULL means the element was absent; '' means it was present and empty.
    source_first_name   TEXT,
    source_middle_name  TEXT,
    source_last_name    TEXT,
    source_nickname     TEXT,
    source_id           TEXT,
    source_display_name TEXT NOT NULL,
    -- Raw SHA-256 of the canonical source serialization.
    source_fingerprint  BYTEA NOT NULL,
    quality_flags       TEXT[] NOT NULL DEFAULT '{}',
    xml_provenance      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT book_contributor_credit_position_key
        UNIQUE (snapshot_id, role, position),
    CONSTRAINT book_contributor_credit_role_check
        CHECK (role IN ('author', 'translator')),
    CONSTRAINT book_contributor_credit_position_check
        CHECK (position >= 0),
    CONSTRAINT book_contributor_credit_source_fingerprint_check
        CHECK (octet_length(source_fingerprint) = 32),
    -- A contributor without a single non-empty name-bearing child creates no
    -- credit, and the display name keeps no edge XML whitespace.
    CONSTRAINT book_contributor_credit_display_name_check
        CHECK (source_display_name <> ''
               AND source_display_name !~ '^[ \t\n\r]'
               AND source_display_name !~ '[ \t\n\r]$'),
    CONSTRAINT book_contributor_credit_quality_flags_check
        CHECK (array_position(quality_flags, NULL) IS NULL),
    CONSTRAINT book_contributor_credit_provenance_check
        CHECK (jsonb_typeof(xml_provenance) = 'object')
);

-- Fingerprint-scoped manual overrides look credits up by fingerprint.
CREATE INDEX book_contributor_credit_fingerprint_idx
    ON public.book_contributor_credit (source_fingerprint);

CREATE TRIGGER book_contributor_credit_immutable
    BEFORE UPDATE OR DELETE ON public.book_contributor_credit
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation();

-- One book in one run: the extraction job and the history of its result.
CREATE TABLE public.author_metadata_run_item (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id           BIGINT NOT NULL REFERENCES public.author_metadata_run (id) ON DELETE RESTRICT,
    book_id          BIGINT NOT NULL REFERENCES public.opds_catalog_book (id) ON DELETE RESTRICT,
    status           TEXT NOT NULL DEFAULT 'pending',
    snapshot_id      BIGINT,
    lease_owner      UUID,
    lease_expires_at TIMESTAMPTZ,
    attempt_count    INTEGER NOT NULL DEFAULT 0,
    next_attempt_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at      TIMESTAMPTZ,

    CONSTRAINT author_metadata_run_item_run_book_key
        UNIQUE (run_id, book_id),
    CONSTRAINT author_metadata_run_item_snapshot_fkey
        FOREIGN KEY (snapshot_id, book_id)
        REFERENCES public.book_metadata_snapshot (id, book_id) ON DELETE RESTRICT,
    CONSTRAINT author_metadata_run_item_status_check
        CHECK (status IN ('pending', 'extracted', 'extracted_no_author', 'already_current',
                          'entry_missing', 'invalid_fb2', 'unsupported_encoding',
                          'metadata_parse_failed')),
    -- The successful statuses point at a snapshot (already_current at the one
    -- that was current); the error statuses keep only the attempt.
    CONSTRAINT author_metadata_run_item_snapshot_check
        CHECK ((status IN ('extracted', 'extracted_no_author', 'already_current'))
               = (snapshot_id IS NOT NULL)),
    CONSTRAINT author_metadata_run_item_finished_check
        CHECK ((status = 'pending') = (finished_at IS NULL)),
    -- Owner and expiry are both set or both empty.
    CONSTRAINT author_metadata_run_item_lease_pair_check
        CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),
    CONSTRAINT author_metadata_run_item_lease_terminal_check
        CHECK (status = 'pending' OR lease_owner IS NULL),
    CONSTRAINT author_metadata_run_item_attempt_count_check
        CHECK (attempt_count >= 0)
);

-- Claim order: ready time, then ID, among the run's pending items.
CREATE INDEX author_metadata_run_item_claim_idx
    ON public.author_metadata_run_item (run_id, next_attempt_at, id)
    WHERE status = 'pending';

-- Backs the restrict check when a legacy book is deleted.
CREATE INDEX author_metadata_run_item_book_idx
    ON public.author_metadata_run_item (book_id);

CREATE TRIGGER author_metadata_run_item_updated_at
    BEFORE UPDATE ON public.author_metadata_run_item
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Append-only attempt history of a run item: a retry adds a row and never
-- overwrites the outcome of an earlier one.
CREATE TABLE public.author_metadata_run_item_attempt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_item_id BIGINT NOT NULL REFERENCES public.author_metadata_run_item (id) ON DELETE RESTRICT,
    attempt_no  INTEGER NOT NULL,
    lease_owner UUID NOT NULL,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    outcome     TEXT,
    error_class TEXT,

    CONSTRAINT author_metadata_run_item_attempt_no_key
        UNIQUE (run_item_id, attempt_no),
    CONSTRAINT author_metadata_run_item_attempt_no_check
        CHECK (attempt_no >= 1),
    CONSTRAINT author_metadata_run_item_attempt_outcome_check
        CHECK (outcome IS NULL
               OR outcome IN ('extracted', 'extracted_no_author', 'already_current',
                              'entry_missing', 'invalid_fb2', 'unsupported_encoding',
                              'metadata_parse_failed')),
    CONSTRAINT author_metadata_run_item_attempt_error_class_check
        CHECK (error_class IS NULL OR error_class ~ '^[a-z][a-z0-9_]{0,63}$'),
    -- Open: no result yet. Finished: a terminal outcome, a closed error class,
    -- or both, and never before it started.
    CONSTRAINT author_metadata_run_item_attempt_finished_check
        CHECK (CASE WHEN finished_at IS NULL
                    THEN num_nonnulls(outcome, error_class) = 0
                    ELSE num_nonnulls(outcome, error_class) > 0 AND finished_at >= started_at
               END)
);

CREATE TRIGGER author_metadata_run_item_attempt_immutable
    BEFORE UPDATE OR DELETE ON public.author_metadata_run_item_attempt
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation('finished_at', 'outcome', 'error_class');

CREATE TRIGGER author_metadata_run_item_attempt_closed
    BEFORE UPDATE ON public.author_metadata_run_item_attempt
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_closed_attempt();

-- The administrator's explicit approval of a completed pilot_archive run. A
-- full run may start only against an approval for the same extractor and
-- normalizer versions. The composite foreign key makes the approval match the
-- run it approves and freezes that run's mode, status and versions.
CREATE TABLE public.author_metadata_pilot_approval (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              BIGINT NOT NULL,
    run_mode            TEXT NOT NULL DEFAULT 'pilot_archive',
    run_status          TEXT NOT NULL DEFAULT 'completed',
    extractor_version   TEXT NOT NULL,
    normalizer_version  TEXT NOT NULL,
    -- Audit, deliberately without a foreign key: the approval is immutable,
    -- so ON DELETE SET NULL could never run and would block deleting the
    -- account instead. The ID outlives the account.
    approved_by_user_id BIGINT NOT NULL,
    approved_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT author_metadata_pilot_approval_run_key
        UNIQUE (run_id),
    CONSTRAINT author_metadata_pilot_approval_run_fkey
        FOREIGN KEY (run_id, run_mode, run_status, extractor_version, normalizer_version)
        REFERENCES public.author_metadata_run (id, mode, status, extractor_version, normalizer_version)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT author_metadata_pilot_approval_run_check
        CHECK (run_mode = 'pilot_archive' AND run_status = 'completed'),
    CONSTRAINT author_metadata_pilot_approval_actor_check
        CHECK (approved_by_user_id > 0)
);

CREATE INDEX author_metadata_pilot_approval_versions_idx
    ON public.author_metadata_pilot_approval (extractor_version, normalizer_version);

CREATE TRIGGER author_metadata_pilot_approval_immutable
    BEFORE UPDATE OR DELETE ON public.author_metadata_pilot_approval
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation();
