-- Author normalization pipeline: immutable normalization results, the
-- per-credit resolution (selected / invalid / unresolved / open review) with an
-- append-only audit, immutable manual overrides, the local-normalization queue,
-- the manual review queue and the acceptance-policy classes.
--
-- There is no LLM stream in this project: no LLM job, attempt or provider batch
-- table. The result method enum still carries 'llm' so a later LLM project
-- needs no enum migration.
--
-- Cross-table "same source" rules are composite foreign keys onto
-- (id, source_fingerprint[, role]); the remaining rules that need a lookup live
-- in one consistency trigger on the resolution table.

SET LOCAL lock_timeout = '5s';

-- Target of the composite foreign keys below: a resolution, override or review
-- item names a credit together with its fingerprint and role, so it cannot
-- pair a credit with a result computed from another source, and only author
-- credits enter the pipeline.
ALTER TABLE public.book_contributor_credit
    ADD CONSTRAINT book_contributor_credit_id_fingerprint_role_key
        UNIQUE (id, source_fingerprint, role);

-- Shared guard for rows that are mutable while open and frozen once
-- finished_at is set.
CREATE FUNCTION public.author_metadata_reject_finished() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF (to_jsonb(OLD) ->> 'finished_at') IS NOT NULL THEN
        RAISE EXCEPTION 'rows of % are immutable once finished', TG_TABLE_NAME
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END
$$;

-- An acceptance-policy class: automatic selection is allowed only for a
-- registered (policy_version, decision_class). Registration is a later,
-- separate step; nothing here seeds a row, so the production policy is empty
-- and an empty policy means zero autoaccept.
CREATE TABLE public.author_acceptance_class (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version         TEXT NOT NULL,
    decision_class         TEXT NOT NULL,
    -- The normalizer configuration the evidence was measured on.
    config_version         TEXT NOT NULL,
    -- Raw SHA-256 of the immutable evidence/eval report.
    evidence_report_sha256 BYTEA NOT NULL,
    registered_by_user_id  BIGINT NOT NULL,
    registered_at          TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT author_acceptance_class_key
        UNIQUE (policy_version, decision_class),
    CONSTRAINT author_acceptance_class_policy_version_check
        CHECK (policy_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    CONSTRAINT author_acceptance_class_decision_class_check
        CHECK (decision_class ~ '^[a-z][a-z0-9_.]{0,63}$'),
    CONSTRAINT author_acceptance_class_config_version_check
        CHECK (config_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    CONSTRAINT author_acceptance_class_evidence_check
        CHECK (octet_length(evidence_report_sha256) = 32),
    CONSTRAINT author_acceptance_class_actor_check
        CHECK (registered_by_user_id > 0)
);

CREATE TRIGGER author_acceptance_class_immutable
    BEFORE UPDATE OR DELETE ON public.author_acceptance_class
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation();

-- The lexical result for one normalization input. Not a person and not a
-- canonical author. Immutable: a correction is a new row.
CREATE TABLE public.contributor_normalization_result (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_fingerprint    BYTEA NOT NULL,
    -- Automatic results only: SHA-256 over fingerprint and both versions.
    normalization_key     BYTEA,
    extractor_version     TEXT,
    normalizer_version    TEXT,
    result_schema_version TEXT NOT NULL,
    method                TEXT NOT NULL,
    kind                  TEXT NOT NULL,
    status                TEXT NOT NULL,
    decision_class        TEXT,
    given_name            TEXT,
    additional_names      TEXT[] NOT NULL DEFAULT '{}',
    family_name           TEXT,
    nickname              TEXT,
    prefix                TEXT,
    suffix                TEXT,
    display_name          TEXT,
    sort_name             TEXT,
    search_key            TEXT,
    script                TEXT,
    quality_flags         TEXT[] NOT NULL DEFAULT '{}',
    -- The admin who wrote a manual result. Audit, so no foreign key: the row
    -- is immutable and must outlive the account.
    created_by_user_id    BIGINT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Targets of composite foreign keys: a pointer to a result always names
    -- the source it was computed from (and, for overrides, its method; for
    -- jobs, its key).
    CONSTRAINT contributor_normalization_result_id_fingerprint_key
        UNIQUE (id, source_fingerprint),
    CONSTRAINT contributor_normalization_result_id_fingerprint_method_key
        UNIQUE (id, source_fingerprint, method),
    CONSTRAINT contributor_normalization_result_id_key_key
        UNIQUE (id, normalization_key),
    CONSTRAINT contributor_normalization_result_method_check
        CHECK (method IN ('structured', 'rules', 'llm', 'manual')),
    CONSTRAINT contributor_normalization_result_kind_check
        CHECK (kind IN ('person', 'collective', 'unknown', 'malformed')),
    CONSTRAINT contributor_normalization_result_status_check
        CHECK (status IN ('normalized', 'unresolved', 'invalid')),
    -- Empty or punctuation garbage is malformed and never a valid name.
    CONSTRAINT contributor_normalization_result_malformed_check
        CHECK (kind <> 'malformed' OR status = 'invalid'),
    CONSTRAINT contributor_normalization_result_fingerprint_check
        CHECK (octet_length(source_fingerprint) = 32),
    -- Automatic results carry their key, both exact versions and a decision
    -- class, and no actor; a manual result carries an actor and none of the
    -- automatic inputs, so a normalizer version change never invalidates it.
    -- coalesce: a comparison with NULL must fail the check, not pass it.
    CONSTRAINT contributor_normalization_result_provenance_check
        CHECK (coalesce(CASE method
                   WHEN 'manual' THEN num_nonnulls(normalization_key, extractor_version, normalizer_version) = 0
                                      AND created_by_user_id > 0
                   ELSE octet_length(normalization_key) = 32
                        AND extractor_version ~ '^[^[:space:]](.*[^[:space:]])?$'
                        AND normalizer_version ~ '^[^[:space:]](.*[^[:space:]])?$'
                        AND created_by_user_id IS NULL
                        AND decision_class IS NOT NULL
               END, false)),
    CONSTRAINT contributor_normalization_result_schema_version_check
        CHECK (result_schema_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    CONSTRAINT contributor_normalization_result_decision_class_check
        CHECK (decision_class IS NULL OR decision_class ~ '^[a-z][a-z0-9_.]{0,63}$'),
    -- ISO 15924 code, or mixed when several letter scripts occur.
    CONSTRAINT contributor_normalization_result_script_check
        CHECK (script IS NULL OR script ~ '^[A-Z][a-z]{3}$' OR script = 'mixed'),
    -- A normalized result has a display name and a search key.
    CONSTRAINT contributor_normalization_result_normalized_check
        CHECK (status <> 'normalized' OR coalesce(display_name <> '' AND search_key <> '', false)),
    CONSTRAINT contributor_normalization_result_arrays_check
        CHECK (array_position(additional_names, NULL) IS NULL
               AND array_position(quality_flags, NULL) IS NULL)
);

-- One local result per normalization key: any number of credits share it, and
-- concurrent workers converge on the same row.
CREATE UNIQUE INDEX contributor_normalization_result_one_local_per_key
    ON public.contributor_normalization_result (normalization_key)
    WHERE method IN ('structured', 'rules');

CREATE INDEX contributor_normalization_result_fingerprint_idx
    ON public.contributor_normalization_result (source_fingerprint);

CREATE TRIGGER contributor_normalization_result_immutable
    BEFORE UPDATE OR DELETE ON public.contributor_normalization_result
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation();

-- An immutable manual decision for exactly one scope: one author credit, or
-- an exact source fingerprint (which also covers future credits with that
-- fingerprint). An edit is a new override over a new manual result; the newest
-- override of a scope is the active one.
CREATE TABLE public.contributor_manual_override (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_credit_id    BIGINT,
    scope_fingerprint  BYTEA,
    -- The source the override is about: the credit's fingerprint for a credit
    -- scope, the scope itself for a fingerprint scope.
    source_fingerprint BYTEA NOT NULL,
    credit_role        TEXT NOT NULL DEFAULT 'author',
    result_id          BIGINT NOT NULL,
    result_method      TEXT NOT NULL DEFAULT 'manual',
    created_by_user_id BIGINT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Target of the resolution's foreign key: the selected result must be
    -- the override's own result.
    CONSTRAINT contributor_manual_override_id_result_key
        UNIQUE (id, result_id),
    CONSTRAINT contributor_manual_override_scope_check
        CHECK (num_nonnulls(scope_credit_id, scope_fingerprint) = 1),
    CONSTRAINT contributor_manual_override_credit_check
        CHECK (scope_credit_id IS NULL OR scope_credit_id > 0),
    CONSTRAINT contributor_manual_override_fingerprint_check
        CHECK (octet_length(source_fingerprint) = 32
               AND (scope_fingerprint IS NULL OR scope_fingerprint = source_fingerprint)),
    CONSTRAINT contributor_manual_override_role_check
        CHECK (credit_role = 'author'),
    CONSTRAINT contributor_manual_override_method_check
        CHECK (result_method = 'manual'),
    CONSTRAINT contributor_manual_override_actor_check
        CHECK (created_by_user_id > 0),
    CONSTRAINT contributor_manual_override_credit_fkey
        FOREIGN KEY (scope_credit_id, source_fingerprint, credit_role)
        REFERENCES public.book_contributor_credit (id, source_fingerprint, role) ON DELETE RESTRICT,
    CONSTRAINT contributor_manual_override_result_fkey
        FOREIGN KEY (result_id, source_fingerprint, result_method)
        REFERENCES public.contributor_normalization_result (id, source_fingerprint, method) ON DELETE RESTRICT
);

CREATE INDEX contributor_manual_override_credit_idx
    ON public.contributor_manual_override (scope_credit_id, id)
    WHERE scope_credit_id IS NOT NULL;

CREATE INDEX contributor_manual_override_fingerprint_idx
    ON public.contributor_manual_override (scope_fingerprint, id)
    WHERE scope_fingerprint IS NOT NULL;

CREATE TRIGGER contributor_manual_override_immutable
    BEFORE UPDATE OR DELETE ON public.contributor_manual_override
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation();

-- Where one author credit stands. Every current author credit ends in exactly
-- one state:
--   selected   — a result is selected, automatically (registered class) or by
--                a credit/fingerprint override;
--   invalid    — the result is invalid (malformed source);
--   unresolved — closed reason, optionally with the proposal it rests on;
--   review     — an open review item decides it, optionally with a proposal.
-- Rows change as decisions are made; every change is appended to the audit by
-- trigger, and rows are never deleted.
CREATE TABLE public.book_contributor_credit_selection (
    credit_id          BIGINT PRIMARY KEY,
    source_fingerprint BYTEA NOT NULL,
    credit_role        TEXT NOT NULL DEFAULT 'author',
    state              TEXT NOT NULL,
    result_id          BIGINT,
    basis              TEXT,
    override_id        BIGINT,
    policy_version     TEXT,
    unresolved_reason  TEXT,
    -- NULL for a decision of the pipeline itself.
    decided_by_user_id BIGINT,
    decided_at         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT book_contributor_credit_selection_credit_fkey
        FOREIGN KEY (credit_id, source_fingerprint, credit_role)
        REFERENCES public.book_contributor_credit (id, source_fingerprint, role) ON DELETE RESTRICT,
    CONSTRAINT book_contributor_credit_selection_result_fkey
        FOREIGN KEY (result_id, source_fingerprint)
        REFERENCES public.contributor_normalization_result (id, source_fingerprint) ON DELETE RESTRICT,
    CONSTRAINT book_contributor_credit_selection_override_fkey
        FOREIGN KEY (override_id, result_id)
        REFERENCES public.contributor_manual_override (id, result_id) ON DELETE RESTRICT,
    CONSTRAINT book_contributor_credit_selection_role_check
        CHECK (credit_role = 'author'),
    CONSTRAINT book_contributor_credit_selection_state_check
        CHECK (state IN ('selected', 'invalid', 'unresolved', 'review')),
    CONSTRAINT book_contributor_credit_selection_basis_check
        CHECK (basis IS NULL OR basis IN ('automatic', 'fingerprint_override', 'credit_override')),
    CONSTRAINT book_contributor_credit_selection_reason_check
        CHECK (unresolved_reason IS NULL
               OR unresolved_reason IN ('policy_not_registered', 'normalizer_failed', 'review_left_unresolved')),
    -- What each state requires and forbids.
    CONSTRAINT book_contributor_credit_selection_shape_check
        CHECK (CASE state
                   WHEN 'selected' THEN result_id IS NOT NULL AND basis IS NOT NULL AND unresolved_reason IS NULL
                   WHEN 'invalid' THEN result_id IS NOT NULL AND basis IS NULL AND unresolved_reason IS NULL
                   WHEN 'unresolved' THEN basis IS NULL AND unresolved_reason IS NOT NULL
                   ELSE basis IS NULL AND unresolved_reason IS NULL
               END),
    -- Automatic selection names the policy it was allowed by; an override
    -- selection names the override.
    CONSTRAINT book_contributor_credit_selection_basis_shape_check
        CHECK (CASE basis
                   WHEN 'automatic' THEN override_id IS NULL AND policy_version IS NOT NULL
                   WHEN 'fingerprint_override' THEN override_id IS NOT NULL AND policy_version IS NULL
                   WHEN 'credit_override' THEN override_id IS NOT NULL AND policy_version IS NULL
                   ELSE override_id IS NULL AND policy_version IS NULL
               END),
    CONSTRAINT book_contributor_credit_selection_actor_check
        CHECK (decided_by_user_id IS NULL OR decided_by_user_id > 0)
);

CREATE INDEX book_contributor_credit_selection_state_idx
    ON public.book_contributor_credit_selection (state, unresolved_reason);

-- Rules a CHECK cannot see because they read other rows. It runs as an AFTER
-- constraint trigger, so the row's own CHECKs and foreign keys report first
-- and this only judges rows that are well-formed on their own.
CREATE FUNCTION public.book_contributor_credit_selection_check() RETURNS trigger
    LANGUAGE plpgsql AS $$
DECLARE
    res public.contributor_normalization_result%ROWTYPE;
    ovr public.contributor_manual_override%ROWTYPE;
    credit_extractor text;
BEGIN
    IF NEW.result_id IS NULL THEN
        RETURN NULL;
    END IF;
    SELECT * INTO res FROM public.contributor_normalization_result WHERE id = NEW.result_id;

    IF NEW.state = 'invalid' AND res.status <> 'invalid' THEN
        RAISE EXCEPTION 'book_contributor_credit_selection: an invalid credit must rest on an invalid result'
            USING ERRCODE = 'check_violation';
    END IF;
    IF NEW.state = 'selected' AND res.status = 'invalid' THEN
        RAISE EXCEPTION 'book_contributor_credit_selection: an invalid result cannot be selected'
            USING ERRCODE = 'check_violation';
    END IF;

    -- An automatic result is about one normalization input: the credit's own
    -- extractor version, not merely the same fingerprint.
    IF res.method <> 'manual' THEN
        SELECT s.extractor_version INTO credit_extractor
        FROM public.book_contributor_credit c
        JOIN public.book_metadata_snapshot s ON s.id = c.snapshot_id
        WHERE c.id = NEW.credit_id;
        IF credit_extractor IS DISTINCT FROM res.extractor_version THEN
            RAISE EXCEPTION 'book_contributor_credit_selection: result extractor version differs from the credit''s snapshot'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    IF NEW.basis = 'automatic' THEN
        IF res.method = 'manual' THEN
            RAISE EXCEPTION 'book_contributor_credit_selection: a manual result is selected through its override'
                USING ERRCODE = 'check_violation';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM public.author_acceptance_class a
            WHERE a.policy_version = NEW.policy_version
              AND a.decision_class = res.decision_class
              AND a.config_version = res.normalizer_version) THEN
            RAISE EXCEPTION 'book_contributor_credit_selection: decision class is not registered in the acceptance policy'
                USING ERRCODE = 'check_violation';
        END IF;
    ELSIF NEW.basis IS NOT NULL THEN
        SELECT * INTO ovr FROM public.contributor_manual_override WHERE id = NEW.override_id;
        IF NEW.basis = 'credit_override' AND ovr.scope_credit_id IS DISTINCT FROM NEW.credit_id THEN
            RAISE EXCEPTION 'book_contributor_credit_selection: a credit override applies only to its own credit'
                USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.basis = 'fingerprint_override' AND ovr.scope_fingerprint IS NULL THEN
            RAISE EXCEPTION 'book_contributor_credit_selection: basis fingerprint_override needs a fingerprint-scoped override'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NULL;
END
$$;

CREATE CONSTRAINT TRIGGER book_contributor_credit_selection_consistency
    AFTER INSERT OR UPDATE ON public.book_contributor_credit_selection
    FOR EACH ROW EXECUTE FUNCTION public.book_contributor_credit_selection_check();

-- A resolution belongs to its credit for good: only the decision changes, and
-- the row never goes away. Moving it to another credit would drop the first
-- credit's accounting without an audit transition and hand the second a
-- predecessor it never had.
CREATE TRIGGER book_contributor_credit_selection_identity
    BEFORE UPDATE OR DELETE ON public.book_contributor_credit_selection
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation(
        'state', 'result_id', 'basis', 'override_id', 'policy_version',
        'unresolved_reason', 'decided_by_user_id', 'decided_at');

-- Append-only history of every resolution change, written by trigger so no
-- writer can change a resolution without leaving the record.
CREATE TABLE public.book_contributor_credit_selection_audit (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    credit_id          BIGINT NOT NULL REFERENCES public.book_contributor_credit (id) ON DELETE RESTRICT,
    previous_state     TEXT,
    previous_result_id BIGINT REFERENCES public.contributor_normalization_result (id) ON DELETE RESTRICT,
    state              TEXT NOT NULL,
    result_id          BIGINT REFERENCES public.contributor_normalization_result (id) ON DELETE RESTRICT,
    basis              TEXT,
    override_id        BIGINT REFERENCES public.contributor_manual_override (id) ON DELETE RESTRICT,
    policy_version     TEXT,
    unresolved_reason  TEXT,
    decided_by_user_id BIGINT,
    recorded_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX book_contributor_credit_selection_audit_credit_idx
    ON public.book_contributor_credit_selection_audit (credit_id, id);

CREATE TRIGGER book_contributor_credit_selection_audit_immutable
    BEFORE UPDATE OR DELETE ON public.book_contributor_credit_selection_audit
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation();

CREATE FUNCTION public.book_contributor_credit_selection_record() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND NEW IS NOT DISTINCT FROM OLD THEN
        RETURN NULL;
    END IF;
    INSERT INTO public.book_contributor_credit_selection_audit
        (credit_id, previous_state, previous_result_id, state, result_id, basis, override_id,
         policy_version, unresolved_reason, decided_by_user_id)
    VALUES
        (NEW.credit_id,
         CASE WHEN TG_OP = 'UPDATE' THEN OLD.state END,
         CASE WHEN TG_OP = 'UPDATE' THEN OLD.result_id END,
         NEW.state, NEW.result_id, NEW.basis, NEW.override_id,
         NEW.policy_version, NEW.unresolved_reason, NEW.decided_by_user_id);
    RETURN NULL;
END
$$;

CREATE TRIGGER book_contributor_credit_selection_audited
    AFTER INSERT OR UPDATE ON public.book_contributor_credit_selection
    FOR EACH ROW EXECUTE FUNCTION public.book_contributor_credit_selection_record();

-- The local normalization queue: one job per normalization key, shared by all
-- author credits with that input. Lease columns carry the same names and
-- rules as author_metadata_run_item.
CREATE TABLE public.contributor_normalization_job (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    normalization_key  BYTEA NOT NULL,
    source_fingerprint BYTEA NOT NULL,
    extractor_version  TEXT NOT NULL,
    normalizer_version TEXT NOT NULL,
    status             TEXT NOT NULL DEFAULT 'pending',
    result_id          BIGINT,
    last_error_class   TEXT,
    lease_owner        UUID,
    lease_expires_at   TIMESTAMPTZ,
    attempt_count      INTEGER NOT NULL DEFAULT 0,
    next_attempt_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at        TIMESTAMPTZ,

    CONSTRAINT contributor_normalization_job_key
        UNIQUE (normalization_key),
    -- The job's result is the result of the job's own key.
    CONSTRAINT contributor_normalization_job_result_fkey
        FOREIGN KEY (result_id, normalization_key)
        REFERENCES public.contributor_normalization_result (id, normalization_key) ON DELETE RESTRICT,
    CONSTRAINT contributor_normalization_job_key_check
        CHECK (octet_length(normalization_key) = 32 AND octet_length(source_fingerprint) = 32),
    CONSTRAINT contributor_normalization_job_versions_check
        CHECK (extractor_version ~ '^[^[:space:]](.*[^[:space:]])?$'
               AND normalizer_version ~ '^[^[:space:]](.*[^[:space:]])?$'),
    CONSTRAINT contributor_normalization_job_status_check
        CHECK (status IN ('pending', 'completed', 'failed')),
    CONSTRAINT contributor_normalization_job_outcome_check
        CHECK (CASE status
                   WHEN 'completed' THEN result_id IS NOT NULL
                   WHEN 'failed' THEN result_id IS NULL AND last_error_class IS NOT NULL
                   ELSE result_id IS NULL
               END),
    CONSTRAINT contributor_normalization_job_error_class_check
        CHECK (last_error_class IS NULL OR last_error_class ~ '^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT contributor_normalization_job_finished_check
        CHECK ((status = 'pending') = (finished_at IS NULL)),
    CONSTRAINT contributor_normalization_job_lease_pair_check
        CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),
    CONSTRAINT contributor_normalization_job_lease_terminal_check
        CHECK (status = 'pending' OR lease_owner IS NULL),
    CONSTRAINT contributor_normalization_job_attempt_count_check
        CHECK (attempt_count >= 0)
);

CREATE INDEX contributor_normalization_job_claim_idx
    ON public.contributor_normalization_job (next_attempt_at, id)
    WHERE status = 'pending';

CREATE TRIGGER contributor_normalization_job_updated_at
    BEFORE UPDATE ON public.contributor_normalization_job
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- A job keeps the input it was created for; only its progress changes.
CREATE TRIGGER contributor_normalization_job_identity
    BEFORE UPDATE ON public.contributor_normalization_job
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation(
        'status', 'result_id', 'last_error_class', 'lease_owner', 'lease_expires_at',
        'attempt_count', 'next_attempt_at', 'updated_at', 'finished_at');

-- The same rule for the extraction queue from migration 23: a run item stays
-- the item of its run and book. Deletion is left to its foreign keys.
CREATE TRIGGER author_metadata_run_item_identity
    BEFORE UPDATE ON public.author_metadata_run_item
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation(
        'status', 'snapshot_id', 'lease_owner', 'lease_expires_at',
        'attempt_count', 'next_attempt_at', 'updated_at', 'finished_at');

-- Append-only attempt history of a local job, same shape and guards as the
-- extraction attempts.
CREATE TABLE public.contributor_normalization_job_attempt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      BIGINT NOT NULL REFERENCES public.contributor_normalization_job (id) ON DELETE RESTRICT,
    attempt_no  INTEGER NOT NULL,
    lease_owner UUID NOT NULL,
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    outcome     TEXT,
    error_class TEXT,

    CONSTRAINT contributor_normalization_job_attempt_no_key
        UNIQUE (job_id, attempt_no),
    CONSTRAINT contributor_normalization_job_attempt_no_check
        CHECK (attempt_no >= 1),
    CONSTRAINT contributor_normalization_job_attempt_outcome_check
        CHECK (outcome IS NULL OR outcome IN ('completed', 'failed')),
    CONSTRAINT contributor_normalization_job_attempt_error_class_check
        CHECK (error_class IS NULL OR error_class ~ '^[a-z][a-z0-9_]{0,63}$'),
    CONSTRAINT contributor_normalization_job_attempt_finished_check
        CHECK (CASE WHEN finished_at IS NULL
                    THEN num_nonnulls(outcome, error_class) = 0
                    ELSE num_nonnulls(outcome, error_class) > 0 AND finished_at >= started_at
               END)
);

CREATE TRIGGER contributor_normalization_job_attempt_immutable
    BEFORE UPDATE OR DELETE ON public.contributor_normalization_job_attempt
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation('finished_at', 'outcome', 'error_class');

CREATE TRIGGER contributor_normalization_job_attempt_closed
    BEFORE UPDATE ON public.contributor_normalization_job_attempt
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_finished();

-- The manual review queue, scoped like an override: one author credit or an
-- exact fingerprint. At most one open item per scope and reason; a closed item
-- is history and does not change again.
CREATE TABLE public.contributor_review_item (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_credit_id      BIGINT,
    scope_fingerprint    BYTEA,
    source_fingerprint   BYTEA NOT NULL,
    credit_role          TEXT NOT NULL DEFAULT 'author',
    reason               TEXT NOT NULL,
    decision_class       TEXT,
    proposal_result_id   BIGINT,
    status               TEXT NOT NULL DEFAULT 'open',
    resolution           TEXT,
    resolution_result_id BIGINT,
    resolved_by_user_id  BIGINT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at          TIMESTAMPTZ,

    CONSTRAINT contributor_review_item_scope_check
        CHECK (num_nonnulls(scope_credit_id, scope_fingerprint) = 1),
    CONSTRAINT contributor_review_item_credit_check
        CHECK (scope_credit_id IS NULL OR scope_credit_id > 0),
    CONSTRAINT contributor_review_item_fingerprint_check
        CHECK (octet_length(source_fingerprint) = 32
               AND (scope_fingerprint IS NULL OR scope_fingerprint = source_fingerprint)),
    CONSTRAINT contributor_review_item_role_check
        CHECK (credit_role = 'author'),
    CONSTRAINT contributor_review_item_reason_check
        CHECK (reason IN ('ambiguous_decision', 'incompatible_manual_schema')),
    CONSTRAINT contributor_review_item_decision_class_check
        CHECK (decision_class IS NULL OR decision_class ~ '^[a-z][a-z0-9_.]{0,63}$'),
    CONSTRAINT contributor_review_item_status_check
        CHECK (status IN ('open', 'closed')),
    CONSTRAINT contributor_review_item_resolution_check
        CHECK (resolution IS NULL
               OR resolution IN ('accepted', 'edited', 'classified', 'left_unresolved', 'retried')),
    -- Open: nothing decided. Closed: a resolution, a time and, except for a
    -- retry handed back to the normalizer, the admin who made it.
    CONSTRAINT contributor_review_item_closed_check
        CHECK (coalesce(CASE status
                   WHEN 'open' THEN num_nonnulls(resolution, resolution_result_id, resolved_by_user_id, finished_at) = 0
                   ELSE resolution IS NOT NULL AND finished_at IS NOT NULL AND finished_at >= created_at
                        AND (resolved_by_user_id > 0 OR resolution = 'retried')
               END, false)),
    CONSTRAINT contributor_review_item_credit_fkey
        FOREIGN KEY (scope_credit_id, source_fingerprint, credit_role)
        REFERENCES public.book_contributor_credit (id, source_fingerprint, role) ON DELETE RESTRICT,
    CONSTRAINT contributor_review_item_proposal_fkey
        FOREIGN KEY (proposal_result_id, source_fingerprint)
        REFERENCES public.contributor_normalization_result (id, source_fingerprint) ON DELETE RESTRICT,
    CONSTRAINT contributor_review_item_resolution_result_fkey
        FOREIGN KEY (resolution_result_id, source_fingerprint)
        REFERENCES public.contributor_normalization_result (id, source_fingerprint) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX contributor_review_item_one_open_per_credit
    ON public.contributor_review_item (scope_credit_id, reason)
    WHERE status = 'open' AND scope_credit_id IS NOT NULL;

CREATE UNIQUE INDEX contributor_review_item_one_open_per_fingerprint
    ON public.contributor_review_item (scope_fingerprint, reason)
    WHERE status = 'open' AND scope_fingerprint IS NOT NULL;

-- Stable review pagination by (created_at, id).
CREATE INDEX contributor_review_item_open_page_idx
    ON public.contributor_review_item (created_at, id)
    WHERE status = 'open';

CREATE TRIGGER contributor_review_item_immutable
    BEFORE UPDATE OR DELETE ON public.contributor_review_item
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_mutation(
        'status', 'resolution', 'resolution_result_id', 'resolved_by_user_id', 'finished_at');

CREATE TRIGGER contributor_review_item_closed
    BEFORE UPDATE ON public.contributor_review_item
    FOR EACH ROW EXECUTE FUNCTION public.author_metadata_reject_finished();
