import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

/*
 * The frontend had no linter between leaving create-react-app, which supplied
 * one inside react-scripts, and this file. In that window unused imports and
 * whole unimported components accumulated unnoticed, because tsc reports
 * neither.
 *
 * The rules below are deliberately narrow: correctness and dead code, not
 * style. Formatting is not policed here — there is no formatter in this project
 * and a linter arguing about it would only produce noise across a codebase that
 * predates it.
 */
export default tseslint.config(
    {
        // src/shared/ui is generated by the shadcn CLI but edited here — the
        // dialog's colours and the drawer's stacking are local decisions — so it
        // is linted like anything else. It currently reports nothing.
        ignores: ['build/**', 'coverage/**', 'node_modules/**'],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            ecmaVersion: 2022,
            globals: globals.browser,
        },
        plugins: {
            'react-hooks': reactHooks,
            'react-refresh': reactRefresh,
        },
        rules: {
            ...reactHooks.configs.recommended.rules,

            // An unused import is the signal that went missing; it is what let
            // five dead components sit in the tree. Underscore-prefixed
            // arguments stay allowed, since they document a signature.
            '@typescript-eslint/no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],

            // any defeats the point of the typed API layer built in phase 3.
            '@typescript-eslint/no-explicit-any': 'warn',

            /*
             * react-hooks 7 added this, and it lands on a pattern used in about
             * twenty places here: mirroring something — a prop, a context, a
             * fetch — into state from an effect. Each costs a second render, and
             * several are worth unpicking, but they are spread across the admin
             * screens and the contexts and cannot be sorted out in one sitting.
             *
             * A warning keeps every one of them in view without failing the gate
             * on code that predates the rule. Raise it to error once the list is
             * worked through.
             */
            'react-hooks/set-state-in-effect': 'warn',

            'no-console': ['warn', { allow: ['warn', 'error'] }],
        },
    },
    {
        // Tests reach for globals the browser does not have and mock freely.
        files: ['**/*.test.{ts,tsx}', 'src/setupTests.ts'],
        languageOptions: {
            globals: { ...globals.browser, ...globals.node },
        },
        rules: {
            'react-refresh/only-export-components': 'off',
        },
    },
    {
        // Vite config and other tooling run in node.
        files: ['*.config.{js,ts}', 'vite.config.ts'],
        languageOptions: {
            globals: globals.node,
        },
    },
);
