basePath: /api
definitions:
  api.ExportAnswer:
    properties:
      books:
        items:
          $ref: '#/definitions/models.Book'
        type: array
      langs:
        $ref: '#/definitions/models.Languages'
        type: object
      length:
        type: integer
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.Author:
    properties:
      full_name:
        type: string
      id:
        type: integer
      lang_code:
        type: integer
      search_full_name:
        type: string
    type: object
  models.Book:
    properties:
      annotation:
        type: string
      authors:
        items:
          $ref: '#/definitions/models.Author'
        type: array
      avail:
        type: integer
      cat_type:
        type: string
      catalog_id:
        type: integer
      docdate:
        type: string
      filename:
        type: string
      filesize:
        type: integer
      format:
        type: string
      id:
        type: integer
      lang:
        type: string
      lang_code:
        type: integer
      path:
        type: string
      registerdate:
        type: string
      search_title:
        type: string
      series:
        items:
          $ref: '#/definitions/models.Series'
        type: array
      title:
        type: string
    type: object
  models.BookDownload:
    properties:
      book_id:
        type: integer
      format:
        type: string
    required:
    - book_id
    - format
    type: object
  models.Languages:
    items:
      properties:
        count:
          type: integer
        language:
          type: string
      type: object
    type: array
  models.LoggedInUser:
    properties:
      token:
        type: string
      username:
        type: string
    type: object
  models.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      invite:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - invite
    - password
    - username
    type: object
  models.Series:
    properties:
      id:
        type: integer
      lang_code:
        type: integer
      search_ser:
        type: string
      ser:
        type: string
    type: object
info:
  contact:
    email: aladex@gmail.com
    name: API Support
  description: GOPDS API implementation to django service
  license: {}
  title: GOPDS API
  version: "1.0"
paths:
  /books/authors:
    get:
      consumes:
      - application/json
      description: возвращает JSON с авторами
      parameters:
      - description: Just token without bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Author ID
        in: query
        name: author
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ExportAnswer'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: возвращает JSON с авторами
  /books/file:
    post:
      consumes:
      - application/json
      description: returns file of book in answered type
      parameters:
      - description: Book Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.BookDownload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.BookDownload'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: returns file of book in answered type
      tags:
      - files
  /books/list:
    get:
      consumes:
      - application/json
      description: возвращает JSON с книгами
      parameters:
      - description: Just token without bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: Limit
        in: query
        name: limit
        required: true
        type: integer
      - description: Offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Title of book
        in: query
        name: title
        type: string
      - description: Author ID
        in: query
        name: author
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ExportAnswer'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: возвращает JSON с книгами
  /login:
    post:
      consumes:
      - application/json
      description: Login method for token generation
      parameters:
      - description: Login Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoggedInUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Returns an user and token for header
      tags:
      - login
  /logout:
    get:
      consumes:
      - application/json
      description: Метод разлогина
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoggedInUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Метод разлогина
      tags:
      - login
  /register:
    post:
      consumes:
      - application/json
      description: creates a new user
      parameters:
      - description: User Data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/string'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: creates a new user
      tags:
      - login
  /self-user:
    get:
      consumes:
      - application/json
      description: Метод для получения информации по пользователю
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoggedInUser'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Метод для получения информации по пользователю
      tags:
      - login
swagger: "2.0"
