# Name of the job
name: Build and push Docker image

# Trigger the job on push events to tags matching 'v*' (e.g. v1.0, v20.15.10)
on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    # Run the job on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Extract the version from the Git tag
      - name: Extract version from Git tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      # Set up QEMU, which allows the Docker daemon to build and run multi-architecture images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # Set up Docker Buildx, which enables building and pushing of multi-architecture images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push the Docker image
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          # Set the build context to the current directory
          context: .
          # Push the built image to DockerHub
          push: true
          # Set the tags for the built image
          tags: |
            aladex/gopds-api:${{ steps.get_version.outputs.VERSION }}
            aladex/gopds-api:latest
